version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/django_with_llm
  - source: /.env
    destination: /home/ubuntu/django_with_llm
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/django_with_llm
    pattern: '**'
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 10000
      runas: root
